export const CREATE_FILE_CONTENT = 'I am fresh and young'
export const FS_PATH = './files'
export const CREATE_FILE_NAME = 'fresh.txt'
export const FOLDER_COPY_NAME_NEW = './files_copy'
export const FILE_NAME_TO_RENAME = './files_copy/wrongFilename.txt'
export const FILE_NAME_TO_RENAME_NEW = './files_copy/properFilename.md'
